export const SET_SUBCATEGORY = 'SET_SUBCATEGORY';
export const SUCCESS_SUBCATEGORY = 'SUCCESS_SUBCATEGORY';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SUCCESS_CATEGORY = 'SUCCESS_CATEGORY';
